export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "File", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    dominantColor: "#3b82f6",
    typeIcons: ["Code", "Link", "File"],
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    dominantColor: "#3b82f6",
    typeIcons: ["Code", "Link"],
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: false,
    itemCount: 5,
    dominantColor: "#6b7280",
    typeIcons: ["File", "StickyNote"],
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: true,
    itemCount: 24,
    dominantColor: "#3b82f6",
    typeIcons: ["Code", "Terminal", "Link", "StickyNote"],
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    dominantColor: "#f97316",
    typeIcons: ["Terminal", "Link"],
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    dominantColor: "#8b5cf6",
    typeIcons: ["Sparkles", "Terminal", "File"],
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useauth Hook",
    contentType: "text" as const,
    content: "Custom authentication hook for React applications",
    description: "Custom authentication hook for React applications",
    typeId: "type_snippet",
    typeName: "Snippet",
    typeColor: "#3b82f6",
    typeIcon: "Code",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    tags: ["react", "auth", "hooks"],
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "text" as const,
    content: "Fetch wrapper with exponential backoff retry logic",
    description: "Fetch wrapper with exponential backoff retry logic",
    typeId: "type_snippet",
    typeName: "Snippet",
    typeColor: "#3b82f6",
    typeIcon: "Code",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    tags: ["api", "error-handling", "fetch"],
    createdAt: new Date("2025-01-12"),
  },
  {
    id: "item_3",
    title: "Docker Compose Dev Stack",
    contentType: "text" as const,
    content: "docker-compose.yml for local dev environment with Postgres and Redis",
    description: "docker-compose.yml for local dev environment with Postgres and Redis",
    typeId: "type_command",
    typeName: "Command",
    typeColor: "#f97316",
    typeIcon: "Terminal",
    isFavorite: true,
    isPinned: false,
    language: "yaml",
    tags: ["docker", "postgres", "redis"],
    createdAt: new Date("2025-01-10"),
  },
  {
    id: "item_4",
    title: "Explain This Code",
    contentType: "text" as const,
    content: "You are a senior software engineer. Explain the following code clearly and concisely.",
    description: "System prompt for explaining code snippets",
    typeId: "type_prompt",
    typeName: "Prompt",
    typeColor: "#8b5cf6",
    typeIcon: "Sparkles",
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ["ai", "code-review"],
    createdAt: new Date("2025-01-08"),
  },
  {
    id: "item_5",
    title: "Next.js App Router Docs",
    contentType: "url" as const,
    content: null,
    url: "https://nextjs.org/docs/app",
    description: "Official Next.js App Router documentation",
    typeId: "type_link",
    typeName: "Link",
    typeColor: "#10b981",
    typeIcon: "Link",
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ["nextjs", "docs"],
    createdAt: new Date("2025-01-06"),
  },
  {
    id: "item_6",
    title: "Git Stash Workflow",
    contentType: "text" as const,
    content: "git stash push -m 'description' && git stash pop",
    description: "Quick stash and pop workflow for switching branches",
    typeId: "type_command",
    typeName: "Command",
    typeColor: "#f97316",
    typeIcon: "Terminal",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    tags: ["git", "workflow"],
    createdAt: new Date("2025-01-04"),
  },
];

export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_link: 8,
};
